### PR TITLE
Restructure Dockerfile to use ascend-ros-base as base image

### PR DESCRIPTION
**Pull request by akselaase**
Modifies the existing docker image to use ascend-ros-base as the base image. 

Note:
- Depending on [docker-ascend-ros-base!5](https://github.com/AscendNTNU/docker-ascend-ros-base/pull/5) to be merged. Current base image in dockerfile is not compatible, things won't build.

Questions:
- Should a docker-compose.yml file also be included? 
- README should probably be updated to include docker build/run instructions (those instructions are simpler by providing docker-compose file)
- Should the Dockerfile and docker-compose reside in this repo, or should we have a common repo (AscendNTNU/dockerfiles) with all common dockerfiles? Challenges with keeping the dockerfile in this repo is that if there are any breaking changes in ascend-ros-base it isn't easy to track those changes across repos. This can be prevented by tagging ascend-ros-base with a V1 tag or similar. (Done - using a specific commit tag to ascend-ros-base now)
- @Torjusba, do you want to fix some CI actions?

### CODE REVIEW

**Comment by Torjusba** [comment]
- I think including a docker-compose.yml is good practice, yes. 

- In my opinion, keeping dockerfiles in a central repo is harder to maintain. Referencing a specific image tag is a good solution for stability, but might lead to a lot of overhead when updating ascend-ros-base? What do you think is the best base image practice @oestby ?

- I will do CI

**Comment by oestby** [comment]
I think that keeping Dockerfiles together with their respective repos are the best solution, while more general Dockerfiles like Ascends base image should probably have its own repo. This will cause the least amount of headache unless you want a spotless commit log.

Tagging is probably a good idea, but I am not sure what the best solution for a versioning scheme is. I believe that the base repo might stabilize quite quickly, so it might be sufficient to start with using the 'latest' tag and start tagging with versions when we agree the base image is stable enough?

**Comment by akselaase** [comment]
If we start using 'latest' we might have trouble down the road if we're going to modify the base image. But, we probably have so few repos using the base image anyway that it won't be a problem manually updating them, so I'm okay with using 'latest' anyway. If we eventually create a 'v1' tag we'll have to manually update every instance of 'latest' though (but again, it's probably <5 repos, only fluid and ai21 that I can think of).

A benefit of storing the dockerfiles together would be to simplify CI/CD. Whenever ascend-ros-base is updated, an action could run that automatically builds the other images in the repo (and verifies that they build correctly). Maybe that's possible if the dockerfiles are split across repos as well, but probably a bit more difficult.

**Comment by oestby** [comment]
I am not sure I understand what problems using latest will cause down the road?
My reasoning is that using tags early in the development process is a bit cumbersome because you often introduce breaking changes pretty often so until the base image is a bit more stable you just treat it as unstable and take extra care when you rebuild the child images. Then when the base is stable you introduce tags and a more strict routine on new releases of the base image.

If we have a monorepo for Dockerfiles we either need to manage their respective git dependencies in the Dockerfile, or in the GitHub actions. Or we need to manage the collection of the Dockerfile in the actions of the child project, if I am not forgetting something. Which I believe is a little less elegant.

Maybe we should continue this discussion in person? It is a very interesting discussion! 😁

**Comment by akselaase** [comment]
Agree, either Wednesday evening or Friday then!

**Comment by akselaase** [comment]
😢

**Pull request closed without merging**
